data:
  input_path: data/raw/df_ventilation_imputed_unfiltered.pkl
  output_dir: data/preprocessed/ventilation
  id_column: encounterId
  index_column: timestamp
  columns:
    numerical:
      - age
      - weight
      - PIM
      - hoursVentilated
      - HR
      - MAP
      - RR(measured)
      - etCO2
      - temp
      - SpO2
      - systolicBP
      - meanBP
      - diastolicBP
      - pH
      - PCO2
      - baseExcess
      - lactate
      - HCO3
      - WBC
      - Neutrophil
      - Hb
      - fluidBalance
      - FiO2
      - PIP
      - RR(set)
      - PEEP(set)
      - inspTime
      - PS
      - TVbyWeight
      - RRRatio
      - IERatio
      - deltaP
      - mPower
      - SFRatio
    categorical:
      - diagnosis
      - ethnicity
    binary:
      - gender
      - NMB
      - sedation
      - furosemide
      - vasoActive
      - steroid
      - ventMode_PC
      - ventMode_PS
      - ventMode_NIV
      - ventMode_Highflow
      - ventMode_NoSupport

preprocessing:
  excluding:
    rules:
      - column: ifDeceased
        operation: "=="
        value: 1
      - column: LOV
        operation: "<="
        value: 6
      - column: LOV
        operation: ">"
        value: 672

split:
  test_size: 0.2
  val_size: 0.2
  random_state: 12